### PR TITLE
Presses the nth specified button

### PR DESCRIPTION
**Pull request by gimler**
* [x] add press nth button
* [x] add tests for follow nth button
* [x] add tests for follow nth link
* [x] remove duplicate code

### CODE REVIEW

**Comment by gimler** [comment]
ping

**Comment by sanpii** [comment]
Can you update `i18n/en.xliff.dist` to add the new definition?

**Comment by gimler** [comment]
@sanpii done

**Comment by sanpii** [comment]
Thank you.

**Pull request merged**
