### PR TITLE
Allow to extend JsonContext

### PR DESCRIPTION
**Pull request by blazarecki**
This PR allow to extend JsonContext and use `getJson()` method.
It also allow to use `inspector` and `httpCallResultPool` properties too.

Now we'll be able to create custom methods which need the method or the properties.

What do you think of this PR ?

### CODE REVIEW

**Comment by sanpii** [comment]
> What do you think of this PR ?

I am not against this idea, but I prefer extend the public interface for a good reason.

Do you have an example?

**Comment by blazarecki** [comment]
If I want to add a new method, for example:

```php
    public function theJsonNodeShouldBeNull(string $node)
    {
        $json = $this->getJson();
        $actual = $this->inspector->evaluate($json, $node);
        if (null !== $actual) {
            throw new \Exception(
                sprintf('The node value is `%s`', json_encode($actual))
            );
        }
    }
```

Then I need to duplicate the `JsonContext` because I need the `getJson()` method and the `inspector` attribute.

If they were protected I will be able to extends JsonContext and add only my custom methods.

**Comment by elkangaroo** [comment]
This would be really useful, I just stumbled upon the same, i.e. getJson() and $inspector being private. +1

**Comment by sanpii** [comment]
Merged, thank you.

**Comment by dupuchba** [comment]
@blazarecki you literally saved my day ^^

**Comment by dupuchba** [comment]
by the way, have you tried to extend `JsonContext` WITH the Symfony extension ? Can't make it work...

**Pull request closed without merging**
