### PR TITLE
RestContext to be extendable

### PR DESCRIPTION
**Pull request by kbsali**
just so we can extend RestContext...

### CODE REVIEW

**Comment by kbsali** [comment]
up @sanpii ! :)

**Comment by kbsali** [comment]
@sanpii, anyway you could merge this PR? :) We are still depending on my fork for our project, not ideal! :)

Thanks!

**Comment by sanpii** [comment]
Can you remove this empty commit https://github.com/Behatch/contexts/pull/166/commits/2c63fbad0965b5d15c356d4ed1fd154e4958ee1d?

**Comment by kbsali** [comment]
done!

**Comment by sanpii** [comment]
Merged, thank you!

**Pull request closed without merging**
