### PR TITLE
Fix $ref resolution problems

### PR DESCRIPTION
**Pull request by araines**
Following issue #95 

In order for the $refs to be resolved correctly within the JSONSchema library, we need to pass a reference to the original JSON object, rather than a copy of its content, when resolving.  This is because the library alters the object when it does its dereferencing.

### CODE REVIEW

**Comment by Trogie** [comment]
Works for me!

**Comment by araines** [comment]
@Trogie : I found that the JSONSchema library was failing silently when it comes to resolution of `$ref`.  i.e. your tests will pass when they should not.

If you take a look at the documented method of dereferencing a schema in the JSON Schema libraries docs, you will see that the contexts here do not set up the library correctly.  Without passing the reference to the JSON object, any dereferencing done is not reflected and is lost.

However, if you have a working example schema test failure which requires correct `$ref` resolution to have taken place, I'd like to see it - I couldn't get this to work without the changes specified here.

**Comment by Trogie** [comment]
I ment the patch works for me. :p

**Comment by araines** [comment]
Ah I completely got the wrong end of the stick!  Thanks for checking it out :)

**Comment by sanpii** [comment]
Can you add a corresponding behat test scenario?

**Comment by araines** [comment]
@sanpii I've added the invalid test case - the test cases already existed but were not actually working properly (due to the silent failures I mentioned earlier), which has meant I've had to add additional contexts to prove things out.  Not ideal, but given you need the feature tests it was the best way I could think to do it.

**Comment by sanpii** [comment]
Rebase & merged. Thank you.

**Pull request closed without merging**
