### PR TITLE
Test recent versions of PHP. Compatibility with PHP7.

### PR DESCRIPTION
**Pull request by dunglas**
Also use the new Travis infrastructure and composer cache.

### CODE REVIEW

**Comment by sanpii** [comment]
Why don’t allow failures for hhvm?

**Comment by dunglas** [comment]
Because HHVM is considered stable now. But if tests fails on it (because ou Atoum?) I can add it to the list.

**Comment by dunglas** [comment]
Any update about this one?

**Comment by jderusse** [comment]
:+1: 
Any news? PHP 7 will be release in the next month, and the composer.json of `Behatch/contexts` for me to run composer commands with `--ignore-platform-reqs`

**Comment by blazarecki** [comment]
:+1: 

Any idea when this PR will be merged ?

PS: Thanks @jderusse for `--ignore-platform-reqs`.

**Comment by sanpii** [comment]
> Any idea when this PR will be merged ?

Sorry I had not seen the update allowing failure for hhvm.

**Pull request closed without merging**
