### PR TITLE
Improve system context

### PR DESCRIPTION
**Pull request by tophsic**
Hi,

To test a command line tool, it would be nice to be able to check time of execution and the output, so I implemented 4 new steps in system context :

* `command should last less than :seconds seconds`
* `command should not last less than :seconds seconds`
* `(I )should see on output ":text"`
* `(I )should not see on output ":text"`

As I write this PR, I think about another step : `output should be :text`...

### CODE REVIEW

**Comment by sanpii** [comment]
Nice work, thank you :smiley: 

> As I write this PR, I think about another step : output should be :text

I prefer `output should be:` with a multiline text (`PyStringNode`).

**Comment by tophsic** [comment]
For sure :grin: new PR is coming...

**Comment by tophsic** [comment]
Besides, we can get rid of `preg_quote` calls

**Comment by tophsic** [comment]
As you propose `output should be:`, do you think it is possible to keep the regex idea ?

Or maybe `output should be:` action will check exact output and `output should contains :regex` will act as I implemented.

What do you think?

**Comment by sanpii** [comment]
> What do you think?

I prefer two differents actions for plain and regex match.

**Pull request closed without merging**
