### PR TITLE
Json-schema update

### LINKED ISSUE #190: Remove the phar package
Nobody downloads the phar package. Furthermore this help to fix #181 

| Version | Download count |
| --- | --- |
| 2.5 | 0 |
| 2.4 | 0 |
| 2.3 | 0 |
| 2.2 | 1 |
| 2.1 | 1 |
| 1.4 | 2 |
| 1.3 | 3 |
| 1.2 | 2 |

Source: https://api.github.com/repos/behatch/contexts/releases

### PR DESCRIPTION
**Pull request by sanpii**
Fix #190 and #181.

### CODE REVIEW

**Comment by sanpii** [comment]
Ready to merge \o/

**Comment by nicolasheraly** [comment]
@sanpii can you merge it ?

**Comment by sanpii** [comment]
@nicolasheraly I completely forgotten this, thank you.

**Comment by nicolasheraly** [comment]
@sanpii  thanks !

**Pull request closed without merging**
