### PR TITLE
JSON steps with type comparision

### PR DESCRIPTION
**Pull request by dunglas**
Add new steps for the JSON context allowing to test against types.

### CODE REVIEW

**Comment by sanpii** [comment]
This PR add many definitions for doing the same thing. I prefer work on #115 and correctly handle types. What do you think?

**Comment by dunglas** [comment]
@sanpii This is not the same usage.

JSON is typed. `"null"` and `null` aren't the same thing and it's currently impossible to differentiate the two. This PR adds this possibility. This is similar to PHP's `==` (#115) and `===` (#116).

**Comment by dunglas** [comment]
@sanpii any update about this PR? (I've a project where testing is data type is important.)

**Comment by theofidry** [comment]
+1 for this one, it really helps when testing an API and is kind of a pain to redo it for every API when this could be refactored here, which is where it should be.

**Comment by sanpii** [comment]
Ok, I thought about this during my vacation. We can add only one step:

    @Then the JSON node :node should be equal to the :type :value

And leave the current ``the JSON node :node should be equal to :text`` as is (to prevent breaking compatibility) and remove it in version 3.0.

What do you think?

**Comment by dunglas** [comment]
IMO we can even leave the current version (with my patch) in 3.0. It's convenient in some cases (like `==` is with PHP).

About your proposal, the sentence in natural language will be weird for `null`:
`the JSON node "foo" should be equal to the null null`
`the JSON node "foo" should be equal to the boolean false`

I also think that:
`And the JSON node "root[1]" should be true` looks better `than And the JSON node "root[1]" should be the boolean true` but I can live with it.

**Comment by sanpii** [comment]
> About your proposal, the sentence in natural language will be weird for `null`

You’re right, for this case a separate step seems a good idea.

**Comment by anjalirana** [comment]
any update guys?

**Comment by MLKiiwy** [comment]
Any update please from the maintainer ? 
There issue (#132) have multiple PR : #116 , #140 , #115 
I think the best solution is this PR #116 ! 

So can we merge it and release if tests pass ?

**Comment by sanpii** [comment]
@MLKiiwy thanks for your help. It’s merged.

**Pull request closed without merging**
