### PR TITLE
Fix checking filename

### PR DESCRIPTION
**Pull request by cve**

### CODE REVIEW

**Comment by cve** [comment]
Can someone merge this?

**Comment by sanpii** [comment]
> Can someone merge this?

I’m waiting for other feedbacks.

I don’t understand the improvement provided by this modification, however this forbids absolute paths.

**Comment by cve** [comment]
I have a standard Symfony project structure, and a *.feature file like:

````gherkin
Feature: [...]

    [...]
    And the JSON should be valid according to the schema "draft_card_item.json"
````

The file draft_card_item.json is in the same location as .feature

After run I get exception:

````
The JSON schema doesn't exist
````

**Comment by cve** [comment]
Ok, I found the problem...

I'm using PhpStorm and it's default working directory for running Behat is features instead of project root. After setting that my path to file should be features/draft_card_item.json which works in PhpStorm test runner and from command line, thanks and sorry :)

**Pull request closed without merging**
