### PR TITLE
@Then the JSON node :node should match :regexp

### PR DESCRIPTION
**Pull request by gajdaw**
I need to match JSON nodes against some regexps from time to time.
Maybe others will find that useful too.

### CODE REVIEW

**Comment by sanpii** [comment]
I dislike the idea mixing json and regex, I think the json schema is a better solution.

But I'm not against it, I will merge according to the :+1: and :-1:.

**Comment by gajdaw** [comment]
Hi.
Sometimes I need to generate random records. To force uniqueness for fields like name, title or caption, I usually append date, time or timestamp. Thus, I get the record with name set to something like 'lorem ipsum 2016.06.20 14:34:11 12345214321".

With "@Then the JSON node :node should match :regexp" I can verify that the database contains the record that matches the given pattern and I do not have to store the values "2016.06.20 14:34:11 12345214321" anywhere.

**Comment by sanpii** [comment]
@gajdaw you can make the same think with a [json schema](http://json-schema.org/):

```
{
	"title": "Example Schema",
	"type": "object",
	"properties": {
		"title": {
			"type": "string",
			"pattern": "…"
		}
	}
}
```

**Comment by gajdaw** [comment]
Wow! I didn't know! Thanks a lot!

**Comment by aledeg** [comment]
@sanpii It's working well, but it's very verbose just to validate a single data.

**Pull request closed without merging**
