### PR TITLE
Test for browserkit client

### PR DESCRIPTION
**Pull request by eljam**
- I add some test for the browserkit client (2.3) version as there is a BC break on the getRequest() method 
- I add a test on the setHttpHeader method for browserkitDriver

Hope that's helping

### CODE REVIEW

**Comment by sanpii** [comment]
I made a mistake in the name of the `Request` classes. I fixed it but this breaks your PR, sorry.

> I add some test for the browserkit client (2.3) version as there is a BC break on the getRequest() method

`getRequest()` is available in browserkit 2.2 and 2.3, isn’t it?

> I add a test on the setHttpHeader method for browserkitDriver

I use the `Request\BrowserKit` class for this.

**Comment by eljam** [comment]
The problem is that ```getRequest()``` in browserKit 2.3 return ```Symfony\Component\HttpFoundation\Request``` and you need to use ```getInternalRequest()``` see https://github.com/symfony/BrowserKit/blob/2.3/Client.php#L323 to get a ```Symfony\Component\BrowserKit\Request``` which have the ```getServer()``` method.

In 2.2 the ```$request``` variable is equal as the ```$internalRequest``` see https://github.com/symfony/BrowserKit/blob/2.2/Client.php#L256, so if you do a ```getServer()``` on the ```$client``` you always have the ```Symfony\Component\BrowserKit\Request```

About ```Request\BrowserKit```

The class is ok, the problem is that the method setHeader use on ```$client``` is not available in ```BrowserKit\Client``` see https://github.com/symfony/BrowserKit/blob/master/Client.php#L127-L130   but in ```goutteClient``` it's ok see https://github.com/FriendsOfPHP/Goutte/blob/master/Goutte/Client.php#L52-L57

This is why i add this test
```php
        // Use for goutte Driver only
        if (method_exists($client, 'setHeader')) {
            $client->setHeader($name, $value);
        } else {
            // Browserkit
            $client->setServerParameter($name, $value);
        }
```

**Comment by eljam** [comment]
I update the PR for ```setHttpHeader``` method for browserKit class only as you already add the right method for goutte

**Comment by sanpii** [comment]
> I update the PR for setHttpHeader method for browserKit class only as you already add the right method for goutte

Ok, now I understand, but travis doesn’t agree with you.

**Comment by eljam** [comment]
Should be fine now. I reset the last commit.

**Comment by eljam** [comment]
That's ok for you @sanpii ?

**Comment by sanpii** [comment]
Merged :)

**Pull request closed without merging**
