### PR TITLE
Fix array parameters

### PR DESCRIPTION
**Pull request by YoannChabert**
This will fix a BC break with sending POST request with array #261 & #264

### CODE REVIEW

**Comment by raoulclais** [comment]
@YoannChabert , Are you still working on this ? Can you make the tests green ?

If you don't have the time, I can have a look at it.

**Comment by YoannChabert** [comment]
@raoulclais all is green now :)

**Comment by Simperfit** [comment]
@sanpii do you have some time to review this ?
thanks :)

**Review by Simperfit — APPROVED** [review]

**Comment by YoannChabert** [comment]
any news ? @sanpii

**Comment by geoffrey-brier** [comment]
Would be great to have this feature merged :rocket: 

Any plans to merge it @sanpii ?

**Comment by geoffrey-brier** [comment]
The only thing I see is that it could be improved slightly to handle files as well, otherwise great work :+1:

**Comment by raoulclais** [comment]
I still need this

**Pull request closed without merging**
