### PR TITLE
Rename behat.yml-dist to behat.yml.dist

### PR DESCRIPTION
**Pull request by iamluc**
With this change, it is not required anymore to copy behat's configuration if your system is compatible.

### CODE REVIEW

**Comment by sanpii** [comment]
You can simple remove the `cp` commad from `.travis.yml`, `behat.yml.dist` is a default filename.

**Comment by iamluc** [comment]
Yes, but the file is modified below by:
```

**Comment by iamluc** [comment]
Yes but the file is modified below by
```
sed -i 's/Sanpi\\Behatch\\Extension/behatch_contexts.phar/' behat.yml
```

And I don't think we should modify `behat.yml.dist` as the file is tracked by git

**Comment by sanpii** [comment]
> And I don't think we should modify `behat.yml.dist` as the file is tracked by git

You’re right. It’s merged.

**Pull request closed without merging**
