### PR TITLE
Altering the way headers are set

### PR DESCRIPTION
**Pull request by araines**
This seems to work for me where as the current implementation does not.  See issue #105

### CODE REVIEW

**Comment by matts2cant** [comment]
This actually break things for me, i get this error as there is no setHeader method on the Symfony\Bundle\FrameworkBundle\Client class

PHP Fatal error:  Call to undefined method Symfony\Bundle\FrameworkBundle\Client::setHeader() in /home/project/vendor/behatch/contexts/src/Context/RestContext.php on line 195

On the other hand, the setRequestHeader is available on Mink's DriverInterface since 2012. 

Below are my dependencies versions :

"require": {
        "php": ">=5.5.0",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "doctrine/migrations": "1.0.*@dev",
        "doctrine/doctrine-migrations-bundle": "2.1.*@dev",
        "doctrine/data-fixtures": "1.0.*@dev",
        "doctrine/doctrine-fixtures-bundle": "2.2.*@dev",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "phpspec/phpspec": "2.0.*@dev",
        "behat/behat": "3.0.*@dev",
        "behat/mink": "1.6.*@dev",
        "behat/mink-extension": "2.0.*@dev",
        "behat/mink-browserkit-driver":  "1.2.*@dev",
        "behat/symfony2-extension": "2.0.*@dev",
        "behatch/contexts": "dev-master"
    },

Could you consider reverting this commit please ?

**Comment by matts2cant** [comment]
Are these lines even needed since #06c075a ?

**Comment by EmmanuelVella** [comment]
Same issue here

**Comment by araines** [comment]
I was using this with goutte.  If this is causing wider problems, I'm happy with it being reverted - will pick it up again and look in to why my particular problem was occurring.

For the record, here are my dependencies:

```
    "require": {
        "felixkiss/uniquewith-validator": "~1.1",
        "jlapp/swaggervel": "dev-master",
        "laravel/framework": "4.2.*",
        "laravelbook/ardent": "dev-fix_unique_with"
    },
    "require-dev": {
        "behat/behat": "~3.0",
        "behat/mink-goutte-driver": "~1.1",
        "behatch/contexts": "dev-master",
        "phpspec/phpspec": "~2.0",
        "phpunit/phpunit": "~4.1",
        "way/generators": "2.*"
    },
```

**Pull request merged**
